import type * as monaco from "monaco-editor/esm/vs/editor/editor.api"

export default {
  base: "vs",
  inherit: false,
  rules: [
    { token: "keyword", foreground: "ff922b" },
    { token: "delimiter", foreground: "868e96" },
    { token: "label", foreground: "91a7ff" },
    { token: "label.external", foreground: "f06595" },
    { token: "modulePath", foreground: "ffe066" },
    { token: "transcription", foreground: "bac8ff" },
    { token: "comment", foreground: "adb5bd" },
    { token: "description", foreground: "adb5bd", fontStyle: "italic" },
    { token: "number", foreground: "38d9a9" },
    { token: "partOfSpeech", foreground: "38d9a9" },
    { token: "modifier.positive", foreground: "a9e34b" },
    { token: "modifier.negative", foreground: "e64980" },
    { token: "trait.label", foreground: "38d9a9" },
    { token: "trait.label.1", foreground: "38d9a9" },
    { token: "trait.label.2", foreground: "a9e34b" },
    { token: "trait.label.3", foreground: "ffd43b" },
    { token: "trait.member", foreground: "dee2e6" },
    { token: "trait.member.1", foreground: "c3fae8" },
    { token: "trait.member.2", foreground: "e9fac8" },
    { token: "trait.member.3", foreground: "fff3bf" },
  ],
  colors: {
    "editor.foreground": "#ced4da",
    "editor.background": "#212529",
    "editorWidget.foreground": "#adb5bd",
    "editorWidget.background": "#212529",
    "widget.shadow": "#ffa94d20",
    "editor.selectionBackground": '#ffa94d60',
    "editor.inactiveSelectionBackground": '#343a40',
    "editor.lineHighlightBackground": "#343a40",
    "editor.findMatchBackground": "#96f2d7",
    "editor.findMatchHighlightBackground": "#ffd8a8",
    "editorOverviewRuler.findMatchForeground": "#20c99715",
    "editorLineNumber.foreground": "#adb5bd",
    "editorLineNumber.activeForeground": "#ff922b",
    "editorCursor.foreground": "#adb5bd",
    "editorStickyScroll.shadow": "#ffa94d20",
    "editorStickyScrollHover.background": "#343a40",
    "scrollbar.shadow": "#212529",
    "minimap.errorHighlight": "#e64980",
    "minimap.warningHighlight": "#fab005",
    "editorError.foreground": "#e64980",
    "editorWarning.foreground": "#fab005",
  },
} satisfies monaco.editor.IStandaloneThemeData
