import type * as monaco from "monaco-editor/esm/vs/editor/editor.api"

export default {
  base: "vs",
  inherit: false,
  rules: [
    { token: "keyword", foreground: "0ca678" },
    { token: "delimiter", foreground: "9AA2AA" },
    { token: "label", foreground: "d6336c" },
    { token: "label.external", foreground: "6741d9" },
    { token: "modulePath", foreground: "f76707" },
    { token: "transcription", foreground: "f783ac" },
    { token: "comment", foreground: "adb5bd" },
    { token: "description", foreground: "686F77", fontStyle: "italic" },
    { token: "number", foreground: "22b8cf" },
    { token: "partOfSpeech", foreground: "e67700" },
    { token: "modifier.positive", foreground: "37b24d" },
    { token: "modifier.negative", foreground: "c92a2a" },
    { token: "trait.label", foreground: "5f3dc4" },
    { token: "trait.label.1", foreground: "5f3dc4" },
    { token: "trait.label.2", foreground: "1971c2" },
    { token: "trait.label.3", foreground: "1098ad" },
    { token: "trait.member", foreground: "495057" },
    { token: "trait.member.1", foreground: "5c7cfa" },
    { token: "trait.member.2", foreground: "4dabf7" },
    { token: "trait.member.3", foreground: "3bc9db" },
  ],
  colors: {
    "editor.foreground": "#495057",
    "editor.background": "#f8f9fa",
    "editorWidget.foreground": "#495057",
    "editorWidget.background": "#f8f9fa",
    "widget.shadow": "#087f5b20",
    "editor.selectionBackground": '#12b88660',
    "editor.inactiveSelectionBackground": '#dee2e6',
    "editor.lineHighlightBackground": "#20c99730",
    "editor.findMatchBackground": "#ffd43b",
    "editor.findMatchHighlightBackground": "#fff3bf",
    "editorOverviewRuler.findMatchForeground": "#ffd43b",
    "editorLineNumber.foreground": "#adb5bd",
    "editorLineNumber.activeForeground": "#0ca678",
    "editorCursor.foreground": "#868e96",
    "editorStickyScroll.shadow": "#087f5b20",
    "editorStickyScrollHover.background": "#20c99730",
    "scrollbar.shadow": "#f8f9fa",
    "minimap.errorHighlight": "#c92a2a",
    "minimap.warningHighlight": "#fab005",
    "editorError.foreground": "#c92a2a",
    "editorWarning.foreground": "#fab005",
  },
} satisfies monaco.editor.IStandaloneThemeData
